// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file launcher.proto (package launcher, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message launcher.StatusRequest
 */
export class StatusRequest extends Message<StatusRequest> {
  constructor(data?: PartialMessage<StatusRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "launcher.StatusRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): StatusRequest {
    return new StatusRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): StatusRequest {
    return new StatusRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): StatusRequest {
    return new StatusRequest().fromJsonString(jsonString, options);
  }

  static equals(a: StatusRequest | PlainMessage<StatusRequest> | undefined, b: StatusRequest | PlainMessage<StatusRequest> | undefined): boolean {
    return proto3.util.equals(StatusRequest, a, b);
  }
}

/**
 * @generated from message launcher.StatusReply
 */
export class StatusReply extends Message<StatusReply> {
  /**
   * @generated from field: string state = 1;
   */
  state = "";

  /**
   * @generated from field: string version = 2;
   */
  version = "";

  constructor(data?: PartialMessage<StatusReply>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "launcher.StatusReply";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "state", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "version", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): StatusReply {
    return new StatusReply().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): StatusReply {
    return new StatusReply().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): StatusReply {
    return new StatusReply().fromJsonString(jsonString, options);
  }

  static equals(a: StatusReply | PlainMessage<StatusReply> | undefined, b: StatusReply | PlainMessage<StatusReply> | undefined): boolean {
    return proto3.util.equals(StatusReply, a, b);
  }
}

/**
 * @generated from message launcher.LaunchRequest
 */
export class LaunchRequest extends Message<LaunchRequest> {
  /**
   * @generated from field: string job_id = 1;
   */
  jobId = "";

  constructor(data?: PartialMessage<LaunchRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "launcher.LaunchRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "job_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): LaunchRequest {
    return new LaunchRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): LaunchRequest {
    return new LaunchRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): LaunchRequest {
    return new LaunchRequest().fromJsonString(jsonString, options);
  }

  static equals(a: LaunchRequest | PlainMessage<LaunchRequest> | undefined, b: LaunchRequest | PlainMessage<LaunchRequest> | undefined): boolean {
    return proto3.util.equals(LaunchRequest, a, b);
  }
}

/**
 * @generated from message launcher.LaunchReply
 */
export class LaunchReply extends Message<LaunchReply> {
  /**
   * @generated from field: bool started = 1;
   */
  started = false;

  /**
   * @generated from field: string message = 2;
   */
  message = "";

  constructor(data?: PartialMessage<LaunchReply>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "launcher.LaunchReply";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "started", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 2, name: "message", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): LaunchReply {
    return new LaunchReply().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): LaunchReply {
    return new LaunchReply().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): LaunchReply {
    return new LaunchReply().fromJsonString(jsonString, options);
  }

  static equals(a: LaunchReply | PlainMessage<LaunchReply> | undefined, b: LaunchReply | PlainMessage<LaunchReply> | undefined): boolean {
    return proto3.util.equals(LaunchReply, a, b);
  }
}

/**
 * @generated from message launcher.ProgressRequest
 */
export class ProgressRequest extends Message<ProgressRequest> {
  /**
   * @generated from field: string job_id = 1;
   */
  jobId = "";

  constructor(data?: PartialMessage<ProgressRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "launcher.ProgressRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "job_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ProgressRequest {
    return new ProgressRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ProgressRequest {
    return new ProgressRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ProgressRequest {
    return new ProgressRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ProgressRequest | PlainMessage<ProgressRequest> | undefined, b: ProgressRequest | PlainMessage<ProgressRequest> | undefined): boolean {
    return proto3.util.equals(ProgressRequest, a, b);
  }
}

/**
 * @generated from message launcher.ProgressUpdate
 */
export class ProgressUpdate extends Message<ProgressUpdate> {
  /**
   * @generated from field: string job_id = 1;
   */
  jobId = "";

  /**
   * @generated from field: int32 percent = 2;
   */
  percent = 0;

  /**
   * @generated from field: string status = 3;
   */
  status = "";

  constructor(data?: PartialMessage<ProgressUpdate>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "launcher.ProgressUpdate";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "job_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "percent", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 3, name: "status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ProgressUpdate {
    return new ProgressUpdate().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ProgressUpdate {
    return new ProgressUpdate().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ProgressUpdate {
    return new ProgressUpdate().fromJsonString(jsonString, options);
  }

  static equals(a: ProgressUpdate | PlainMessage<ProgressUpdate> | undefined, b: ProgressUpdate | PlainMessage<ProgressUpdate> | undefined): boolean {
    return proto3.util.equals(ProgressUpdate, a, b);
  }
}

