// This file is auto-generated by tools/generate-ts-client.js - DO NOT EDIT

using System.Text.Json.Serialization;

namespace PuduLauncher;

[JsonSourceGenerationOptions(
    PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase,
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
    WriteIndented = false)]
[JsonSerializable(typeof(global::PuduLauncher.Abstractions.Models.CommandResult<string>))]
[JsonSerializable(typeof(global::PuduLauncher.Abstractions.Models.EventBase))]
[JsonSerializable(typeof(global::PuduLauncher.Models.Commands.GreetCommand))]
[JsonSerializable(typeof(global::PuduLauncher.Models.Events.TimerEvent))]
[JsonSerializable(typeof(global::System.String))]
public partial class AppJsonSerializerContext
{
}
