// This file is auto-generated by tools/generate-ts-client.js - DO NOT EDIT

using System.Text.Json.Serialization;

namespace PuduLauncher;

[JsonSourceGenerationOptions(
    PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase,
    PropertyNameCaseInsensitive = true,
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
    WriteIndented = false)]
[JsonSerializable(typeof(global::PuduLauncher.Abstractions.Models.CommandResult<global::PuduLauncher.Models.Config.Preferences>))]
[JsonSerializable(typeof(global::PuduLauncher.Abstractions.Models.CommandResult<global::System.Collections.Generic.List<global::PuduLauncher.Models.Blog.BlogPost>>))]
[JsonSerializable(typeof(global::PuduLauncher.Abstractions.Models.CommandResult<object>))]
[JsonSerializable(typeof(global::PuduLauncher.Abstractions.Models.CommandResult<string>))]
[JsonSerializable(typeof(global::PuduLauncher.Abstractions.Models.EventBase))]
[JsonSerializable(typeof(global::PuduLauncher.Models.Blog.BlogList))]
[JsonSerializable(typeof(global::PuduLauncher.Models.Blog.BlogPost))]
[JsonSerializable(typeof(global::PuduLauncher.Models.Blog.BlogSection))]
[JsonSerializable(typeof(global::PuduLauncher.Models.Config.Preferences))]
[JsonSerializable(typeof(global::PuduLauncher.Models.Events.ServerListUpdatedEvent))]
[JsonSerializable(typeof(global::PuduLauncher.Models.Events.TimerEvent))]
[JsonSerializable(typeof(global::PuduLauncher.Models.Game.GameServer))]
[JsonSerializable(typeof(global::PuduLauncher.Models.ServerList))]
[JsonSerializable(typeof(global::System.Collections.Generic.List<global::PuduLauncher.Models.Blog.BlogPost>))]
[JsonSerializable(typeof(global::System.String))]
[JsonSerializable(typeof(int))]
[JsonSerializable(typeof(string))]
public partial class JsonCtx
{
}
