// This file is auto-generated by tools/generate-ts-client.js - DO NOT EDIT

using System.Text.Json.Serialization;

namespace PuduLauncher;

[JsonSourceGenerationOptions(
    PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase,
    PropertyNameCaseInsensitive = true,
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
    WriteIndented = false)]
[JsonSerializable(typeof(bool))]
[JsonSerializable(typeof(global::PuduLauncher.Abstractions.Models.CommandResult<bool>))]
[JsonSerializable(typeof(global::PuduLauncher.Abstractions.Models.CommandResult<global::PuduLauncher.Models.Config.Preferences>))]
[JsonSerializable(typeof(global::PuduLauncher.Abstractions.Models.CommandResult<global::System.Collections.Generic.List<global::PuduLauncher.Models.Blog.BlogPost>>))]
[JsonSerializable(typeof(global::PuduLauncher.Abstractions.Models.CommandResult<global::System.Collections.Generic.List<global::PuduLauncher.Models.Changelog.ChangelogEntry>>))]
[JsonSerializable(typeof(global::PuduLauncher.Abstractions.Models.CommandResult<global::System.Collections.Generic.List<global::PuduLauncher.Models.Game.GameServer>>))]
[JsonSerializable(typeof(global::PuduLauncher.Abstractions.Models.CommandResult<global::System.Collections.Generic.List<global::PuduLauncher.Models.Installations.Download>>))]
[JsonSerializable(typeof(global::PuduLauncher.Abstractions.Models.CommandResult<global::System.Collections.Generic.List<global::PuduLauncher.Models.Installations.Installation>>))]
[JsonSerializable(typeof(global::PuduLauncher.Abstractions.Models.CommandResult<object>))]
[JsonSerializable(typeof(global::PuduLauncher.Abstractions.Models.CommandResult<string>))]
[JsonSerializable(typeof(global::PuduLauncher.Abstractions.Models.EventBase))]
[JsonSerializable(typeof(global::PuduLauncher.ContentScanning.Models.MType))]
[JsonSerializable(typeof(global::PuduLauncher.ContentScanning.Models.SandboxConfig))]
[JsonSerializable(typeof(global::PuduLauncher.ContentScanning.Models.ScanLog))]
[JsonSerializable(typeof(global::PuduLauncher.ContentScanning.Models.ScanningTypes.MMemberRef))]
[JsonSerializable(typeof(global::PuduLauncher.ContentScanning.Models.ScanningTypes.MResScope))]
[JsonSerializable(typeof(global::PuduLauncher.ContentScanning.Models.TypeConfig))]
[JsonSerializable(typeof(global::PuduLauncher.ContentScanning.Models.WhitelistFieldDefine))]
[JsonSerializable(typeof(global::PuduLauncher.ContentScanning.Models.WhitelistMethodDefine))]
[JsonSerializable(typeof(global::PuduLauncher.Models.Blog.BlogList))]
[JsonSerializable(typeof(global::PuduLauncher.Models.Blog.BlogPost))]
[JsonSerializable(typeof(global::PuduLauncher.Models.Blog.BlogSection))]
[JsonSerializable(typeof(global::PuduLauncher.Models.Changelog.Change))]
[JsonSerializable(typeof(global::PuduLauncher.Models.Changelog.ChangelogEntry))]
[JsonSerializable(typeof(global::PuduLauncher.Models.Changelog.ChangelogList))]
[JsonSerializable(typeof(global::PuduLauncher.Models.Config.InstallationPreferences))]
[JsonSerializable(typeof(global::PuduLauncher.Models.Config.LauncherPreferences))]
[JsonSerializable(typeof(global::PuduLauncher.Models.Config.Preferences))]
[JsonSerializable(typeof(global::PuduLauncher.Models.Config.ServerPreferences))]
[JsonSerializable(typeof(global::PuduLauncher.Models.Events.DownloadProgressEvent))]
[JsonSerializable(typeof(global::PuduLauncher.Models.Events.DownloadStateChangedEvent))]
[JsonSerializable(typeof(global::PuduLauncher.Models.Events.GameStateChangedEvent))]
[JsonSerializable(typeof(global::PuduLauncher.Models.Events.InstallationsChangedEvent))]
[JsonSerializable(typeof(global::PuduLauncher.Models.Events.ServerListUpdatedEvent))]
[JsonSerializable(typeof(global::PuduLauncher.Models.Events.TimerEvent))]
[JsonSerializable(typeof(global::PuduLauncher.Models.Game.GameServer))]
[JsonSerializable(typeof(global::PuduLauncher.Models.Installations.Download))]
[JsonSerializable(typeof(global::PuduLauncher.Models.Installations.DownloadStartRequest))]
[JsonSerializable(typeof(global::PuduLauncher.Models.Installations.DownloadedInstallation))]
[JsonSerializable(typeof(global::PuduLauncher.Models.Installations.Installation))]
[JsonSerializable(typeof(global::PuduLauncher.Models.Installations.InstallationList))]
[JsonSerializable(typeof(global::PuduLauncher.Models.Installations.LaunchGameRequest))]
[JsonSerializable(typeof(global::PuduLauncher.Models.ServerList))]
[JsonSerializable(typeof(global::System.Collections.Generic.List<global::PuduLauncher.Models.Blog.BlogPost>))]
[JsonSerializable(typeof(global::System.Collections.Generic.List<global::PuduLauncher.Models.Changelog.ChangelogEntry>))]
[JsonSerializable(typeof(global::System.Collections.Generic.List<global::PuduLauncher.Models.Game.GameServer>))]
[JsonSerializable(typeof(global::System.Collections.Generic.List<global::PuduLauncher.Models.Installations.Download>))]
[JsonSerializable(typeof(global::System.Collections.Generic.List<global::PuduLauncher.Models.Installations.Installation>))]
[JsonSerializable(typeof(global::System.Guid))]
[JsonSerializable(typeof(global::System.String))]
[JsonSerializable(typeof(int))]
[JsonSerializable(typeof(string))]
public partial class JsonCtx
{
}
