// @generated by protoc-gen-es v2.10.1 with parameter "target=ts"
// @generated from file launcher.proto (package launcher, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file launcher.proto.
 */
export const file_launcher: GenFile = /*@__PURE__*/
  fileDesc("Cg5sYXVuY2hlci5wcm90bxIIbGF1bmNoZXIiDwoNU3RhdHVzUmVxdWVzdCItCgtTdGF0dXNSZXBseRINCgVzdGF0ZRgBIAEoCRIPCgd2ZXJzaW9uGAIgASgJIh8KDUxhdW5jaFJlcXVlc3QSDgoGYXBwX2lkGAEgASgJIi8KC0xhdW5jaFJlcGx5Eg8KB3N0YXJ0ZWQYASABKAgSDwoHbWVzc2FnZRgCIAEoCSIhCg9Qcm9ncmVzc1JlcXVlc3QSDgoGam9iX2lkGAEgASgJIkEKDlByb2dyZXNzVXBkYXRlEg4KBmpvYl9pZBgBIAEoCRIPCgdwZXJjZW50GAIgASgFEg4KBnN0YXR1cxgDIAEoCTKVAQoITGF1bmNoZXISQAoOU2luZ2xlUmVzcG9uc2USFy5sYXVuY2hlci5TdGF0dXNSZXF1ZXN0GhUubGF1bmNoZXIuU3RhdHVzUmVwbHkSRwoOU3RyZWFtUHJvZ3Jlc3MSGS5sYXVuY2hlci5Qcm9ncmVzc1JlcXVlc3QaGC5sYXVuY2hlci5Qcm9ncmVzc1VwZGF0ZTABQhSqAhFQdWR1TGF1bmNoZXIuR3JwY2IGcHJvdG8z");

/**
 * @generated from message launcher.StatusRequest
 */
export type StatusRequest = Message<"launcher.StatusRequest"> & {
};

/**
 * Describes the message launcher.StatusRequest.
 * Use `create(StatusRequestSchema)` to create a new message.
 */
export const StatusRequestSchema: GenMessage<StatusRequest> = /*@__PURE__*/
  messageDesc(file_launcher, 0);

/**
 * @generated from message launcher.StatusReply
 */
export type StatusReply = Message<"launcher.StatusReply"> & {
  /**
   * @generated from field: string state = 1;
   */
  state: string;

  /**
   * @generated from field: string version = 2;
   */
  version: string;
};

/**
 * Describes the message launcher.StatusReply.
 * Use `create(StatusReplySchema)` to create a new message.
 */
export const StatusReplySchema: GenMessage<StatusReply> = /*@__PURE__*/
  messageDesc(file_launcher, 1);

/**
 * @generated from message launcher.LaunchRequest
 */
export type LaunchRequest = Message<"launcher.LaunchRequest"> & {
  /**
   * @generated from field: string app_id = 1;
   */
  appId: string;
};

/**
 * Describes the message launcher.LaunchRequest.
 * Use `create(LaunchRequestSchema)` to create a new message.
 */
export const LaunchRequestSchema: GenMessage<LaunchRequest> = /*@__PURE__*/
  messageDesc(file_launcher, 2);

/**
 * @generated from message launcher.LaunchReply
 */
export type LaunchReply = Message<"launcher.LaunchReply"> & {
  /**
   * @generated from field: bool started = 1;
   */
  started: boolean;

  /**
   * @generated from field: string message = 2;
   */
  message: string;
};

/**
 * Describes the message launcher.LaunchReply.
 * Use `create(LaunchReplySchema)` to create a new message.
 */
export const LaunchReplySchema: GenMessage<LaunchReply> = /*@__PURE__*/
  messageDesc(file_launcher, 3);

/**
 * @generated from message launcher.ProgressRequest
 */
export type ProgressRequest = Message<"launcher.ProgressRequest"> & {
  /**
   * @generated from field: string job_id = 1;
   */
  jobId: string;
};

/**
 * Describes the message launcher.ProgressRequest.
 * Use `create(ProgressRequestSchema)` to create a new message.
 */
export const ProgressRequestSchema: GenMessage<ProgressRequest> = /*@__PURE__*/
  messageDesc(file_launcher, 4);

/**
 * @generated from message launcher.ProgressUpdate
 */
export type ProgressUpdate = Message<"launcher.ProgressUpdate"> & {
  /**
   * @generated from field: string job_id = 1;
   */
  jobId: string;

  /**
   * @generated from field: int32 percent = 2;
   */
  percent: number;

  /**
   * @generated from field: string status = 3;
   */
  status: string;
};

/**
 * Describes the message launcher.ProgressUpdate.
 * Use `create(ProgressUpdateSchema)` to create a new message.
 */
export const ProgressUpdateSchema: GenMessage<ProgressUpdate> = /*@__PURE__*/
  messageDesc(file_launcher, 5);

/**
 * @generated from service launcher.Launcher
 */
export const Launcher: GenService<{
  /**
   * @generated from rpc launcher.Launcher.SingleResponse
   */
  singleResponse: {
    methodKind: "unary";
    input: typeof StatusRequestSchema;
    output: typeof StatusReplySchema;
  },
  /**
   * @generated from rpc launcher.Launcher.StreamProgress
   */
  streamProgress: {
    methodKind: "server_streaming";
    input: typeof ProgressRequestSchema;
    output: typeof ProgressUpdateSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_launcher, 0);

