// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file launcher.proto (package launcher, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { ProgressRequest, ProgressUpdate, StatusReply, StatusRequest } from "./launcher_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service launcher.Launcher
 */
export const Launcher = {
  typeName: "launcher.Launcher",
  methods: {
    /**
     * @generated from rpc launcher.Launcher.SingleResponse
     */
    singleResponse: {
      name: "SingleResponse",
      I: StatusRequest,
      O: StatusReply,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc launcher.Launcher.StreamProgress
     */
    streamProgress: {
      name: "StreamProgress",
      I: ProgressRequest,
      O: ProgressUpdate,
      kind: MethodKind.ServerStreaming,
    },
  }
} as const;

